language: node_js
dist: trusty
sudo: required
node_js:
  - '12.13.1'
git:
  depth: 1

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - stage: Linting & Unit testing & Building
      name: Linting
      script: npm run lint

      - stage: Linting & Unit testing & Building
      name: Unit tests
      script: npm test

      - stage: Linting & Unit testing & Building
      name: Building
      script: npm build

cache:
  directories:
    - node_modules
